### ISSUE TITLE
Add complex expression support for filter/if/unless helpers

### ISSUE THREAD

**Issue by satyajitnayk** [jaredwray/fumanchu#27]
**Is your feature request related to a problem? Please describe.**

- Like in https://github.com/jaredwray/fumanchu/blob/main/test/array.js#L91 we have expression like `{{#filter array "d"}}AAA{{else}}BBB{{/filter}}` can we add support for the following format too??
- 
```hbs
{{#filter array (gt id 123)}}AAA{{else}}BBB{{/filter}}

{{#filter array ((gt id 123) or (lte price 200))}}AAA{{else}}BBB{{/filter}} // gt, lte are custom helpers

{{#if (gt id 123)}}HI{{else}}BYE{{/if}}

{{#if ((gt id 123) or (lte price 200))}}HI{{else}}BYE{{/if}}
```

**Describe the solution you'd like**

**Comment by satyajitnayk** [comment]
Also https://fumanchu.org/ link not working

**Comment by jaredwray** [comment]
@satyajitnayk - thanks for this suggestion. I was not planning to add that in but if you want to do a pull request and add it that would be great and happy to help on it.

**Comment by satyajitnayk** [comment]
@jaredwray I don't think I will be able to do so, due to certain constrains. But for sure will try it in near future.

**Comment by jaredwray** [comment]
@satyajitnayk - ok. Will close this out till you are ready
