### ISSUE TITLE
package depends on vulnerable packages (lodash.template@4.5.0)

### ISSUE THREAD

**Issue by hkjeffchan** [jaredwray/fumanchu#42]
@jaredwray/fumanchu@1.2.1
  └─┬ helper-for-markdown@1.0.2
    └─┬ remarkable@1.7.4
      └─┬ autolinker@0.28.1
        └─┬ gulp-header@1.8.12
          └── lodash.template@4.5.0

gulp-header  >=1.8.10
  Depends on vulnerable versions of lodash.template

Seems helper-for-markdown is not maintained anymore and still using remarkable@1.7.4. Any chance to upgrade the package?

**Comment by jaredwray** [comment]
@hkjeffchan - interesting idea to just replace it. I created this pull request if you want to contribute: https://github.com/jaredwray/fumanchu/pull/44

**Comment by jaredwray** [comment]
@hkjeffchan - this will go out in the latest release today

**Comment by hkjeffchan** [comment]
lodash.template  *
Severity: high
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
fix available via `npm audit fix`
node_modules/lodash.template
  gulp-header  >=1.8.10
  Depends on vulnerable versions of lodash.template
  node_modules/gulp-header

2 high severity vulnerabilities

└─┬ @jaredwray/fumanchu@1.3.0
  └─┬ helper-md@0.2.2
    └─┬ remarkable@1.7.4
      └─┬ autolinker@0.28.1
        └─┬ gulp-header@1.8.12
          └── lodash.template@4.5.0

Can we remove helper-md? @jaredwray
